/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Daisler;

//import jdk.internal.org.jline.utils.InputStreamReader;
//import jdk.*;
//import nio.*;

import java.net.*;
import java.util.Date;

import javax.print.attribute.standard.JobKOctetsSupported;

import java.io.*;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.lang.*;
import org.jsoup.nodes.Document;
//import java.lang.Object;
import org.jsoup.*;
 

public class App{

    public void SaveFile(URL websiteURL, String path) throws IOException{

        Document websiteContent = getContent(websiteURL);

        contentIntoFile(path, websiteContent);
    }

    private void contentIntoFile(String path, Document s){//Auszugebener Tect in die Datei = out

        PrintWriter out = null;

        Date d = new Date();//akutelles Datum wird in Datumsklasse erfasst

        String DateString;// Datum wird in String gewandelt
        DateString = d.toString();

        File f = new File(DateString);// neue Datei mit Datum als name soll erstellt werden

        try {
        
            out = new PrintWriter(f);


        }catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Dateienfehler");

        }
        out.print(s);
        out.close();
    }

    private Document getContent(URL websiteURL) throws IOException{
        System.out.println(websiteURL);
        
        String websiteURLString = websiteURL.toString();

        Document doc = Jsoup.connect(websiteURLString).get();
        
        Date d = new Date();
        String dateString = d.toString();
        
        System.out.println(dateString);

        String title = dateString;


        System.out.println(title);
        return doc;

    }

    /*
    private String getContent (URL websiteURL) throws IOException{ // Eingeholter Text der Webside 
 
        String newLine = "";
        String text = "";

        try {
            BufferedReader in = new BufferedReader(new InputStreamReader(websiteURL.openStream()));
            System.out.print("Hello World!");

            while (newLine == in.readLine()  != false){
                System.out.print("Hello World!");

                text = text + newLine;
            }
            in.close();

        }catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Websitefehler");}

            System.out.println(text);//gibt Websitetext aus

            return text;
    }

    */



}