/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Daisler;

//import jdk.internal.org.jline.utils.InputStreamReader;
//import jdk.*;
//import nio.*;

import java.net.*;
import java.util.Date;

import javax.print.attribute.standard.JobKOctetsSupported;

import java.io.*; //webistecontent
import java.io.PrintWriter;
import java.time.LocalDate;//Dates
import java.lang.*;
import org.jsoup.nodes.Document;
//import java.lang.Object;
import org.jsoup.*;
 

public class App{

    public void SaveFile(URL websiteURL, String path) throws IOException{

        Document websiteContent = getContent(websiteURL);
        
        contentIntoFile(path, websiteContent);
    }

    private void contentIntoFile(String path, Document s)throws FileNotFoundException{//Auszugebener Tect in die Datei = out

        PrintWriter out = null;

        Date d = new Date();//akutelles Datum wird in Datumsklasse erfasst

        String DateString;// Datum wird in String gewandelt
        DateString = d.toString();

        String title = DateString;

        System.out.println(title);//for testing

        File f = new File(path);// neue Datei mit Datum als name soll erstellt werden
        
        out = new PrintWriter(f);

        try {
        
            out = new PrintWriter(f);


        }catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Dateienfehler");

        }
        out.print(s);
        out.close();
    }

    private Document getContent(URL websiteURL) throws IOException{
        System.out.println(websiteURL);
        
        String websiteURLString = websiteURL.toString();//URl of Webiste will be turned into String

        Document doc = Jsoup.connect(websiteURLString).get(); // Content from Website will be truned into Document
        
        //Date d = new Date(); 
        //String dateString = d.toString(); // Date will be turned into String for Filename
        //System.out.println(dateString); // for testing
        //String title = dateString;
        //System.out.println(title);//for testing
        return doc; // Document with Content of Website will be returned

    }

    /*
    private String getContent (URL websiteURL) throws IOException{ // Eingeholter Text der Webside 
 
        String newLine = "";
        String text = "";

        try {
            BufferedReader in = new BufferedReader(new InputStreamReader(websiteURL.openStream()));
            System.out.print("Hello World!");

            while (newLine == in.readLine()  != false){
                System.out.print("Hello World!");

                text = text + newLine;
            }
            in.close();

        }catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Websitefehler");}

            System.out.println(text);//gibt Websitetext aus

            return text;
    }

    */



}